services:
  server:
    container_name: server_prod
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "45205:45205"
    environment:
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_NAME=studs
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVER_PORT=45205
    restart: unless-stopped
    networks:
      - app_net
 
networks:
  app_net:
    driver: bridge
