events {
  worker_connections 1024;
}

stream {
  upstream my_server {
    server server:9090;
    least_conn;
  }

  server {
    listen 9090;
    proxy_pass my_server;
    proxy_connect_timeout 10s;
    proxy_timeout 1m;
  }
}
